# Generated by Django 5.1.5 on 2025-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
            ],
        ),
    ]
