# Generated by Django 5.1.5 on 2025-02-03 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания поста'),
        ),
    ]
