# Generated by Django 5.1.5 on 2025-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_time_stamp_alter_post_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='name',
            field=models.CharField(blank=True, verbose_name='Название файла'),
        ),
    ]
